spring:
  datasource:
    druid:
      url: jdbc:mysql://127.0.0.1:3306/blog?serverTimezone=UTC&characterEncoding=UTF-8
      username: root
      password: 123456
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    encoding: UTF-8
    mode: HTML5
    cache: false

mybatis:
  type-aliases-package: com.cing.blog.model
  mapper-locations: classpath:mapper/*.xml

mapper:
  identity: MYSQL

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

